"""The generated index that lets prose cite one stable page.

Result provenance changes whenever a landmark is remeasured. Copying run names,
settings, and artifact ids into a dozen documents guarantees that some of them
go stale; linking to one generated page does not. Publication writes that page,
and beside it the machine-readable record of which outputs the manifest owned,
so a later run can recognise an output it no longer owns.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING

from boost_and_broadside.publication.renderer_api import PublicationError

if TYPE_CHECKING:  # pragma: no cover - typing only
    from boost_and_broadside.publication.manifest import PublicationManifest

PROVENANCE_RELATIVE_PATH = Path("docs") / "results" / "provenance.md"
OWNERSHIP_RELATIVE_PATH = Path("docs") / "results" / "provenance.json"

_HEADER = """<!-- Generated by `bnb publish`. Do not edit; edit docs/publications.toml. -->

# Result provenance

Every canonical output below is rendered from the exact artifact named beside
it. Digests are the artifact's identity and aggregate file hashes, truncated for
reading; the artifact directory holds the full recipe and provenance.

| output | renderer | source | description |
|---|---|---|---|
"""


def render_provenance_index(rows: Sequence[str]) -> str:
    """The reader-facing provenance table, in manifest order."""

    return _HEADER + "\n".join(rows) + "\n"


def render_ownership(manifest: PublicationManifest) -> str:
    """The outputs this manifest owns, for the next run's stale check."""

    payload = {
        "schema_version": manifest.schema_version,
        "outputs": sorted(entry.output for entry in manifest.entries),
    }
    return json.dumps(payload, indent=2) + "\n"


def load_ownership(root: str | Path) -> tuple[str, ...]:
    """The outputs the previous run recorded, or nothing on a first run.

    This is the only evidence that an output the manifest has dropped was ever
    canonical, so a record that cannot be read is an error rather than an empty
    one: reading it as "nothing was owned" would turn the stale-output check off
    without saying so. An absent file is different — it genuinely means nothing
    has been published yet — and the record is tracked, so its deletion shows up
    in review.
    """

    path = Path(root) / OWNERSHIP_RELATIVE_PATH
    if not path.is_file():
        return ()
    location = OWNERSHIP_RELATIVE_PATH.as_posix()
    try:
        payload = json.loads(path.read_text())
    except json.JSONDecodeError as error:
        raise PublicationError(
            f"{location} is not valid JSON ({error}); it records which outputs the "
            "manifest owned. Restore it from Git, or delete it to start a fresh record."
        ) from error
    outputs = payload.get("outputs") if isinstance(payload, dict) else None
    if not isinstance(outputs, list) or any(not isinstance(item, str) for item in outputs):
        raise PublicationError(
            f"{location} does not record a list of output paths under 'outputs'; "
            "restore it from Git, or delete it to start a fresh record."
        )
    return tuple(outputs)


__all__ = [
    "OWNERSHIP_RELATIVE_PATH",
    "PROVENANCE_RELATIVE_PATH",
    "load_ownership",
    "render_ownership",
    "render_provenance_index",
]
